=== SergeantQuickscoper/waralang/src/templates/wmapConfig.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Schema for wmapConfig.json",
  "type": "object",
  "properties": {
    "buildingSymbol": {
      "type": "string",
      "minLength": 1,
      "maxLength": 1,
      "description": "Symbol used to denote buildings in the ASCII map.",
      "default":"$"
    },
    "junctionSymbol": {
      "type": "string",
      "minLength": 1,
      "maxLength": 1,
      "description": "Symbol used to denote junctions in the ASCII map. Junctions are cells where an actor can change direction.",
      "default":"+"
    },
    "colliders":{
        "type":"array",
        "items": {
            "type":"string",
            "maxLength": 1,
            "minLength": 1
        },
        "default": ["|", "-", "/", "\\"],
        "minItems": 1,
        "maxItems": 255,
        "description": "Symbols that the actors will collide with."
    },
    "wordSize":{
        "type":"object",
        "properties": {
            "baseAddressSize":{
                "type":"integer",
                "default":5,
                "description": "building code"
            },
            "subAddressSize":{
                "type":"integer",
                "default":11,
                "description": "address of the specific word in the building."
            }
        },
        "required": ["baseAddressSize", "subAddressSize"],
        "description": "word size for primary memory."
    },
    "spawn":{
        "type":"object",
        "properties": {
            "x":{
                "type":"integer",
                "description": "x coordinate of spawn point of actors. x=0 is left border of map",
                "minimum": 0
            },
            "y":{
                "type":"integer",
                "description": "y coordinate of spawn point of actors. y=0 is top border of map",
                "minimum": 0
            },
            "direction":{
                "type":"string",
                "enum":["<", ">", "v", "^"],
                "description": "default direction the actors will move in upon spawning. <: left, >: right, v: down, ^: up"
            }
        },
        "required": ["x", "y", "direction"]
    },
    "buildings":{
        "type": "array",
        "items":{
            "type":"object",
            "properties": {
                "FUNC":{
                    "type":"object",
                    "properties": {
                        "opcodeList":{
                            "type":"array",
                            "description": "OPCODE array for function.",
                            "items": {
                                "type":"string",
                                "minLength": 1
                            }
                        }
                    },
                    "required": ["opcodeList"],
                    "description": "Function."
                },
                "MEM":{
                    "type":"object",
                    "properties": {
                        "baseAddress":{
                            "type":"string",
                            "description": "Base address for building.",
                            "minLength": 1
                        },
                        "size":{
                            "type":"integer",
                            "description": "Number of words this building has."
                        }
                    },
                    "required": ["baseAddress", "size"],
                    "description": "Memory."
                },
                "REG":{
                    "type":"object",
                    "properties": {
                        "baseAddress":{
                            "type":"string",
                            "description": "Base address for building.",
                            "minLength": 1
                        }
                    },
                    "required": ["baseAddress"],
                    "description": "Register."
                }
            },
            "oneOf": [
                {"required":["FUNC"]},
                {"required": ["MEM"]},
                {"required": ["REG"]}
            ]
        }
    }
  },
  "required": ["buildings", "spawn", "buildingSymbol", "junctionSymbol", "colliders", "wordSize"]
}

=== SergeantQuickscoper/waralang/src/templates/wmapConfig.json
{
    "$schema": "./wmapConfig.schema.json",
    "buildingSymbol": "$",
    "junctionSymbol": "+",
    "colliders":  ["|", "-", "/", "\\"],
    "wordSize": {
        "baseAddressSize": 50,
        "subAddressSize": 62
    },
    "spawn": {
        "x": 0,
        "y": 0,
        "direction": ">"
    },
    "buildings": [
        {
            "MEM": {
                "baseAddress": "ISH",
                "size": 1000000000000000000
            }
        },
        {
            "MEM": {
                "baseAddress": "ISH",
                "size": 1000000000000000000
            }
        },
        {
            "MEM": {
                "baseAddress": "ISH",
                "size": 1000000000000000000
            }
        },
        {
            "MEM": {
                "baseAddress": "ISH",
                "size": 1000000000000000000
            }
        },
        {
            "FUNC": {
                "opcodeList": [
                    "ADD",
                    "MULT"
                ]
            }
        },
        {
            "FUNC": {
                "opcodeList": [
                    "ADD"
                ]
            }
        },
        {
            "FUNC": {
                "opcodeList": [
                    "ADD"
                ]
            }
        },
        {
            "REG": {
                "baseAddress": "COUNTRYOVEN"
            }
        }
    ]
}
